# -*- coding: utf-8 -*-
"""Analises_Vendas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dXMjcflCCaf8Y1Pb2f4ttwn2XZG4VcMB
"""

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)import os

"""#Vou carregar os Dados"""

Dados = pd.read_csv("salesdaily.csv")

"""#Verficar a Estrutura

"""

Dados.info()

print(Dados.head(5))

Dados.describe()

Dados["datum"] = pd.to_datetime(Dados["datum"])

"""#1 What are the total sales quantities for each drug category (ATC code)?3	Which three drugs have the highest sales in January 2015, July 2016, September 2017?	4	Which drug has sold the most often in 2017?5	Which drug category has the highest average daily sales?	6	Are respiratory drugs (R03) sold more during specific months?

#1. Qual é o total de vendas de cada categoria de medicamento (código ATC)_
"""

Vendas=["M01AB","M01AE","N02BA", "N02BE", "N05B","N05C", "R03", "R06"]
Vendas_Total=Dados[Vendas].sum()
print(Vendas_Total)

"""#Qual dos medicamentos teve a maior venda total (individual)?"""

Vendas_Total.sort_values(ascending=False)

"""#Quais foram as três drogas mais vendidas em janeiro de 2015, julho de 2016 e setembro de 2017, respectivamente_

#PARA JANEIRO DE 2015
"""

jan_2015 = Dados.loc[
    (Dados['Year'] == 2015) & (Dados['Month'] == 1),
    Vendas
].sum().sort_values(ascending=False)
print(jan_2015.head(3))

"""#PARA SETEMBRO DE 2016"""

julho_2016 = Dados.loc[
    (Dados['Year'] == 2016) & (Dados['Month'] ==6),Vendas].sum().sort_values(ascending=False)
print(julho_2016.head(3))

"""#PARA SETEMBRO DE 2017"""

setembro_2017 = Dados.loc[
    (Dados['Year'] == 2017) & (Dados['Month'] ==9),Vendas].sum().sort_values(ascending=False)
print(setembro_2017.head(3))

"""Qual droga foi mais vendida em 2017?"""

Vendas_2017=Dados[Dados["Year"]==2017][Vendas].sum()
print(Vendas_2017.sort_values(ascending=False))

"""#Qual categoria de droga tem a maior média de vendas diárias?"""

# Definir colunas
Vendas_Medias_Diaria = ["M01AB", "M01AE", "N02BA", "N02BE", "N05B", "N05C", "R03", "R06"]

# 1. Agrupar por dia (soma horas dia)
diario = Dados.groupby(Dados['datum'].dt.date)[Vendas_Medias_Diaria].sum()

# 2. Calcular média do DIÁRIO (não do horário!)
Vendas_Media = diario.mean()

# 3. Ordenar e mostrar
print(Vendas_Media.sort_values(ascending=False))

"""#Os medicamentos respiratórios (R03) são vendidos mais em meses específicos?"""

Vendas_R03=Dados.groupby([Dados["Year"],Dados["Month"]])["R03"].sum()
print(Vendas_R03.sort_values(ascending=False))